name: New feature
description: Suggest or request a new feature
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Please fill out the sections below to properly describe the new feature you are suggesting.
    - type: textarea
      id: description
      attributes:
          label: Describe the feature
          placeholder: A button in the screen X that allows to do Y
      validations:
          required: true
    - type: textarea
      id: rationale
      attributes:
          label: It should be implemented because
          placeholder: It will allow to do Y that is needed for Z
    - type: textarea
      id: context
      attributes:
          label: Additional context
          placeholder: |
              Add any other context or screenshots about the feature request here.
    - type: dropdown
      id: assign
      attributes:
          label: "Would you like to work on this issue?"
          options:
              - "Yes"
    - type: markdown
      attributes:
          value: |
              Thanks for your suggestion! Let's see together if it can be implemented.
